version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo install
    # steps:
  pre_build:
    commands:
      - echo pre_build
    # steps:
  build:
    commands:
      - mvn clean package
      - echo build
    # steps:
  post_build:
    commands:
      - echo post_build
    # steps:
artifacts:
  files:
    - '**/*'
    - target/spring-boot-todo-rest-api-h2-0.0.1-SNAPSHOT.jar
  discard-paths: yes